// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OMS.Infrastructure.Data;

#nullable disable

namespace OMS.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260201190056_UpadatedEntities")]
    partial class UpadatedEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("OMS.Infrastructure.Entities.AppliedDiscountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DiscountCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscountName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceAfter")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiscountCategoryId");

                    b.HasIndex("OrderId");

                    b.ToTable("AppliedDiscounts");
                });

            modelBuilder.Entity("OMS.Infrastructure.Entities.Customer.CustomFieldDefinitionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CustomFieldDefinitions");
                });

            modelBuilder.Entity("OMS.Infrastructure.Entities.Customer.CustomFieldOptionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CustomFieldDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomFieldDefinitionId");

                    b.ToTable("CustomFieldOptions");
                });

            modelBuilder.Entity("OMS.Infrastructure.Entities.Customer.CustomFieldValueEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CustomFieldDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomFieldDefinitionId");

                    b.HasIndex("CustomerId", "CustomFieldDefinitionId")
                        .IsUnique();

                    b.ToTable("CustomerCustomFieldValues");
                });

            modelBuilder.Entity("OMS.Infrastructure.Entities.Customer.CustomerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("OMS.Infrastructure.Entities.Customer.CustomerFieldValueHistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CustomFieldDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValue")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomFieldDefinitionId");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerFieldValueHistory");
                });

            modelBuilder.Entity("OMS.Infrastructure.Entities.DiscountCategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DiscountCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1a2f3b4-c5d6-47e8-9f0a-1234567890ab"),
                            IsActive = true,
                            Name = "PriceList",
                            Priority = 1,
                            Type = 0,
                            Value = 0.05m
                        },
                        new
                        {
                            Id = new Guid("e2b3c4d5-f6a7-48b9-0c1d-2345678901bc"),
                            IsActive = true,
                            Name = "Promotion",
                            Priority = 2,
                            Type = 0,
                            Value = 0.10m
                        },
                        new
                        {
                            Id = new Guid("f3c4d5e6-a7b8-49c0-1d2e-3456789012cd"),
                            IsActive = true,
                            Name = "Coupon",
                            Priority = 3,
                            Type = 1,
                            Value = 10.00m
                        });
                });

            modelBuilder.Entity("OMS.Infrastructure.Entities.OrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OMS.Infrastructure.Entities.AppliedDiscountEntity", b =>
                {
                    b.HasOne("OMS.Infrastructure.Entities.DiscountCategoryEntity", "Category")
                        .WithMany("AppliedDiscounts")
                        .HasForeignKey("DiscountCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OMS.Infrastructure.Entities.OrderEntity", "Order")
                        .WithMany("AppliedDiscounts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OMS.Infrastructure.Entities.Customer.CustomFieldOptionEntity", b =>
                {
                    b.HasOne("OMS.Infrastructure.Entities.Customer.CustomFieldDefinitionEntity", "CustomFieldDefinition")
                        .WithMany("Options")
                        .HasForeignKey("CustomFieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomFieldDefinition");
                });

            modelBuilder.Entity("OMS.Infrastructure.Entities.Customer.CustomFieldValueEntity", b =>
                {
                    b.HasOne("OMS.Infrastructure.Entities.Customer.CustomFieldDefinitionEntity", "CustomFieldDefinition")
                        .WithMany("CustomerValues")
                        .HasForeignKey("CustomFieldDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OMS.Infrastructure.Entities.Customer.CustomerEntity", "Customer")
                        .WithMany("CustomFieldValues")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomFieldDefinition");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("OMS.Infrastructure.Entities.Customer.CustomerFieldValueHistoryEntity", b =>
                {
                    b.HasOne("OMS.Infrastructure.Entities.Customer.CustomFieldDefinitionEntity", "CustomFieldDefinition")
                        .WithMany("ValueHistory")
                        .HasForeignKey("CustomFieldDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OMS.Infrastructure.Entities.Customer.CustomerEntity", "Customer")
                        .WithMany("FieldValueHistory")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomFieldDefinition");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("OMS.Infrastructure.Entities.Customer.CustomFieldDefinitionEntity", b =>
                {
                    b.Navigation("CustomerValues");

                    b.Navigation("Options");

                    b.Navigation("ValueHistory");
                });

            modelBuilder.Entity("OMS.Infrastructure.Entities.Customer.CustomerEntity", b =>
                {
                    b.Navigation("CustomFieldValues");

                    b.Navigation("FieldValueHistory");
                });

            modelBuilder.Entity("OMS.Infrastructure.Entities.DiscountCategoryEntity", b =>
                {
                    b.Navigation("AppliedDiscounts");
                });

            modelBuilder.Entity("OMS.Infrastructure.Entities.OrderEntity", b =>
                {
                    b.Navigation("AppliedDiscounts");
                });
#pragma warning restore 612, 618
        }
    }
}
